name: Daily API Check

on:
  schedule:
    - cron: '0 0 * * *' # 北京时间 08:00
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 下载黑匣子，但不提交它
      - name: Fetch Huya JSON
        run: |
          mkdir -p scripts
          curl -L "https://search.cdn.huya.com/?m=Search&do=getSearchContent&q=%E9%9C%B2%E9%9B%AA&v=4&typ=-5&rows=1" -o scripts/huya_api.json

      - name: Run Python Logic
        run: python scripts/check_api.py

      - name: Git Check & Push
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "ZI-FEI-YU-BOT"
            git config --global user.email "bot@zifeiyu.com"
            
            # 自动升级版本号
            sed -i "s/version: \(.*\)+\(.*\)/echo \"version: \1+\$((\2+1))\"/e" simple_live_app/pubspec.yaml
            
            git add .
            git commit -m "chore: 发现虎牙接口变动，已自动修复并升级版本"
            git push
          else
            echo "接口无变动，今日跳过更新。"
          fi
